### ISSUE TITLE
Creating setup.py for project

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/OdfEdit#1]
As this is a python library, it should be great to :

- Make a setup.py file
- Explore maybe pyinstaller to use it easily on Windows

@eturpault

**Comment by eturpault** [comment]
I don't think that OdfEdit can be considered as a python library, it cannot be called by another python script, it is rather an autonomous application.

**Comment by rousseldenis** [comment]
> I don't think that OdfEdit can be considered as a python library, it has no API which can be called by another python script, it is rather an autonomous application with its own graphical user interface. The Windows and Linux executables that I provided in the repository bin folder have been generated by using pyinstaller.

I wanted to say, there is a generic way of packaging python addons. When that is well done, you can publish it on pypi repository, then (I'm on linux only, so I cannot say for windows), people just launch `pipx install OdfEdit`and that's all! If we mention correctly the libraries dependencies (like lxml, pillow, ....), they will be installed automatically too.

**Comment by eturpault** [comment]
As said in another post, if you agree and you find it useful please put in place a python addons for OdfEdit, I have not the time and currently knowledge to do it. Thank you.

**Comment by eturpault** [comment]
@rousseldenis I would like to use Github Actions to publish automatically new releases of OdfEdit on PyPI. For that I need to create a secret variable to store the token of PyPI, but it seems that I have not the rights to do it in the Settings page.
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
Have you the possibility to grant me more rights on the repository OdfEdit ? Thank you.

**Comment by eturpault** [comment]
@rousseldenis Kind reminder.

**Comment by rousseldenis** [comment]
> @rousseldenis Kind reminder.

Yes. I know you tant to publish it on pypi. I'll try to update this suickly

**Comment by eturpault** [comment]
@rousseldenis : to be able to create a secret variable, I think that I need to be admin in the OdfEdit repository.
[Here ](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects#managing-access-of-an-existing-collaborator-on-your-project)is the procedure to manage access of an existing collaborator. 
Could you please grant me the Admin role in OdfEdit repository ?
Maybe @oleg68 or @larspalo have the rights to do it if you have not the time.
Thanks.

**Comment by oleg68** [comment]
@eturpault 

> Could you please grant me the Admin role in OdfEdit repository ? Maybe @oleg68 or @larspalo have the rights to do it if you have not the time. Thanks.

I'm not familiar with github access setting, but I've tried to send you an invitation with admin access.

![image](https://github.com/GrandOrgue/OdfEdit/assets/11586506/583c4b24-169f-4991-b0f0-ceb1a050dedf)

Please check your access rights.

**Comment by eturpault** [comment]
@oleg68 : thank you, but you have given me Admin rights in the GoOdf repository, whereas I need it in the OdfEdit repository.
I checked in GoOdf, with the Admin level I have access to the security page permitting to define secret variables, so this is what I need.
So could you please grant me the Admin rights in the OdfEdit repository (and you can reduce my rights level in the GoOdf repository where I don't need to be Admin) ?

**Comment by oleg68** [comment]
@eturpault I've tried it at the second time. Please take a check.

**Comment by eturpault** [comment]
Yes now I am Admin in the OdfEdit repository and I have access to the Security pages, thank you !

**Comment by eturpault** [comment]
About the initial comment of this issue :
- OdfEdit is now uploaded in https://pypi.org/project/OdfEdit/, not using a setup.py file as suggested, but using a pyproject.toml file which is recommanded for new projects ([see here](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/)), and using twine tool. Finally I will not use a Github action to perform automatically the upload of OdfEdit files in PyPI as it is quite complex (for me) to put in place.
- OdfEdit executable files are generated using pyinstaller and shared in each release, for Windows and Linux.

@rousseldenis do you agree this issue can be closed ?

**Comment by rousseldenis** [comment]
> @rousseldenis do you agree this issue can be closed ?

@eturpault Yes, of course. But we need to replace this by a pyproject.toml file at root directory.

**Comment by eturpault** [comment]
I have uploaded the file pyproject.toml at the root directory.
