### ISSUE TITLE
[feature] Create an object

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/ODFEdit#15]
Now creating a new object (for example, Rank) with OdFEdit is quite difficult.

I'd like to have a `Create` button that would allow to specify the object type and to maintain the object counts.

For example, when I create a Rank object in a Stop, I expect the new Rank index would be allocated and the NumberOfRanks would be updated in both [Organ] and [Stop999] sections as well as add the Rank999 key in the [Stop999].

**Comment by eturpault** [comment]
Good idea, I add this to my TO DO list, thanks !

**Comment by eturpault** [comment]
Currently to create a new object the steps are : clear the edition area (right click on it and select "Clear all"), write the ID and attributes lines of the new object then press the button "Apply changes", the new object will be added to the ODF with none parent.
I will think about how to implement your request. For sure the objects counters in Organ can be increased, but when one creates a Rank or a Stop, we don't indicate in this Rank or Stop to which Stop or Manual it belongs to respectively, I will try to find a handy way to do it anyway.

**Comment by oleg68** [comment]
> I will try to find a handy way to do it anyway, like a dialog box to indicate which object one wants to create and under which existing parent object.

A possible scenario could be

1. Select a parent object (ex. Stop or Manual)
2. Press a `Create` button
3. Select an object type from a list of available objects.

Another way is to use a pop-up right-click menu.

**Comment by eturpault** [comment]
Similarly when one deletes an object the references to it in other objects should be removed, and the counters updated accordingly.

**Comment by eturpault** [comment]
Hi @oleg68, I have completed the evolution that your requested, adding other possibilities around the objects management and linking between them.
I added several buttons at the top of the edition area : 
- Add : to add a child object to the current selected object (the feature that you requested)
- Parents : to choose the objects of the ODF to which the current selected object has to be linked as parents
- Children : the same a Parents but for Children objects
- Rename : to rename the last three digits of the current selected object
- Delete : was already present in the last releases

With all these actions, OdfEdit takes cares to update automatically the NumberOf attributes in the parent or Organ object and the referencing between the objects.
In this new version I made also some GUI improvements, I added the support of the comments at the end of the lines and the "/" separator in the path. For the HW to GO conversion, now the visible objects of the main panel are described with PanelElement objects.
Here is the v2.3 beta release, could you please test it and give me your feedback / remarks ? Thank you.
[OdfEdit-2.3-beta-linux.zip](https://github.com/GrandOrgue/ODFEdit/files/11116382/OdfEdit-2.3-beta-linux.zip)

**Comment by eturpault** [comment]
Hi @oleg68 , here is a new v2.3 beta3 release with the following changes compared to the previous beta2 : 
- fixes some issue in the new objects linking feature
- permits to select a parent or child object in the area above the selected object edition area
- add a menu (opened with the new button at the left of the Quit button) with a menu item checkbox permitting to ask to convert from HW to GO the unused ranks. This menu will permit to add if necessary other options or features (I think to add a feature to extend the compass of a manual)
Please let me know if you have comments or if you have seen bugs or if you have requests for other features to add.
[OdfEdit-2.3-beta3-linux.zip](https://github.com/GrandOrgue/ODFEdit/files/11153176/OdfEdit-2.3-beta3-linux.zip)
In my Ubuntu virtual machine the GUI of OdfEdit renders bad with big buttons and text, whereas in Windows it is fine. I hope that in your Linux machine the look is good.
I think to publish soon this v2.3 build.
