### ISSUE TITLE
Wrong sources at releases page

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/ODFEdit#22]
When downloading the source files from the Releases page, you get one version earlier than stated. This makes it cumbersome if someone wants to build a specific version on his own.

Please update your sources first on Github, and publish the release after that. In this way, the proper archives will be generated automatically.

Thank you.

**Comment by rousseldenis** [comment]
@kerkovits last release seems synced with sources version. Are you sure you are on the releases page?

https://github.com/GrandOrgue/ODFEdit/releases


Apart of that @eturpault it should be great to have a little bit more pushes on the repository if you can. That can help contributors testing your changes and have feedback on them.

Usually, you can do a commit (and push it) per little functional change you make. Then, the release can embed all those little changes.

**Comment by eturpault** [comment]
Indeed for the last release v2.3 I made an error and the source files accessible from the Release page are not the latest one (even if they seem to be). I don't know how to fix this issue so I let it as it is, sorry for who wanted to download it. I will take care to respect the proper order (sources update then new release publish) for the next release.
@rousseldenis : currently I am doing heavy changes in the HW to GO convertion source code, to implement conditional switches, alternative ranks, tremulants, the build is not ready for tests, I prefer to wait to have reached a stable and testable state before to release it, even for an intermediate release.

**Comment by kerkovits** [comment]
Yes, I am sure. I got a file named as `ODFEdit-2.3.zip`, However, in the `src/OdfEdit.py`, I found version 2.2.

**Comment by rousseldenis** [comment]
> Indeed for the last release v2.3 I made an error and the source files accessible from the Release page are not the latest one (even if they seem to be). I don't know how to fix this issue so I let it as it is, sorry for who wanted to download it. I will take care to respect the proper order (sources update then new release publish) for the next release. @rousseldenis : currently I am doing heavy changes in the HW to GO convertion source code, to implement conditional switches, alternative ranks, tremulants, the build is not ready for tests, I prefer to wait to have reached a stable and testable state before to release it, even for an intermediate release.

What I wanted to say, the repository can be seen as a working place. When developping, it's common to have for instance one branch for one particular feature with few changes in order to validate them quickly and isolate them from other changes in another branch.

That should help also reading the history in commits to see those changes separately and not in one big commit called 'v2.4..'

My two cents
