### ISSUE TITLE
Encapsulate the organ dictionary functionality for reuse

### ISSUE THREAD

**Issue by rnditdev** [GrandOrgue/OdfEdit#27]
Hello,

Firstly, thank you for this wonderful tool. I want to create different related tools, like a graphical console editor, and it would be great to encapsulate the organ dictionary under a separate module/class, so I can import and invoke a method like `builddict (file path)`, end build upon the data structure.

Thank you!

**Comment by eturpault** [comment]
Hello,
Yes with the class C_ODF_DATA you can load, change, link/unlink, rename, delete and save data of an ODF. For the moment I prefer to keep all the code in a single file, it is easier to navigate inside it.

**Comment by eturpault** [comment]
Don't hesitate to ask if you need clarifications on some parts of the code. I always try to comment the code as much as possible, it should be quite understandable.
