### ISSUE TITLE
Correct way to not show any text on images

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/OdfEdit#29]
I notice that the key value pair

DispLabelText=

is frequently used to not display any text on an element. The correct way to do this is by specifying instead:

TextBreakWidth=0

Compare with the GrandOrgue help for verification of this strategy if you're not ready to take my word for it.

**Comment by eturpault** [comment]
I used DispLabelText= empirically, I ignored that the proper way is to use TextBreakWidth=0 when one wants no text displayed, I will fix this in the next OdfEdit release, thanks for the information.

**Comment by eturpault** [comment]
This is fixed in OdfEdit v2.5
