### ISSUE TITLE
Switches that should be referenced from a manual is not

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/OdfEdit#30]
At least when converting the St. Michel en Thiérache, I noticed that the in the manuals, the "stops" that actually are controlled by switches, doesn't list relevant the switch references. This is essential for divisionals to work (without full engaged), and it's also now important for how the switches are listed in the yaml combinations.

**Comment by eturpault** [comment]
I confirm that OdfEdit never puts reference to switches in manual sections, since I believed that it was not mandatory.
Which switches should be referenced in the manual sections : 
1 - only switches which are referenced in stops / couplers sections of the manual
2 - or also all the child switches which are controlling switches of the point 1 ?

**Comment by larspalo** [comment]
If a stop, coupler or tremulant has another function than "Input" then it's controlled by a switch. If a switch is in fact directly allowing control (by user input) over a stop, coupler or tremulant that belongs to that manual - then the switch should be listed under the manual too. Normally, in such use cases, only the switches are presented to the user to interact with and thus also store in combinations.

So, only the switches that allow user control directly, and are used as input source to the stop, coupler or tremulant should be added under the manual. (Think like this: if the switch is presented to the user to interact with _as_ the stop, coupler or tremulant - add it to the relevant manual)

Well, yes it's not mandatory, but it's useful. With Olegs recent work on the yaml combinations, this also takes on a new importance since the switches are not strictly (only) global objects anymore.

**Comment by eturpault** [comment]
By "only the switches that allow user control **directly**" do you mean the switches which allow user control without condition (like the state of another switch) ?

In case of user control with condition, I have these two examples coming from Frankfurt sample set of Sonus Paradisi :  

For this coupler, should we have only the Switch018 mentioned in the manual to which it belongs to ? : 
![image](https://github.com/GrandOrgue/OdfEdit/assets/51839171/26af1f65-09a4-4ef2-a5e3-4f2112b473c9)

For this stop, should we have only the Switch085 mentioned in the manual to which it belongs to ?
![image](https://github.com/GrandOrgue/OdfEdit/assets/51839171/4d931672-365b-47b5-bec2-30434d7c0f02)

**Comment by larspalo** [comment]
I think it's a yes to all of your cases. List that what you think would be appropriate to store in a divisional for that manual.

If a switch is listed in (under) more than one manual for any reason, it's considered to be a global switch. On occasion it might make some sense to include global switches (or other elements) that can affect multiple manuals in all of the manuals affected, this could for instance include tremulants that influence the whole organ.

**Comment by eturpault** [comment]
This issue is fixed, it will be delivered in the next OdfEdit release.

**Comment by eturpault** [comment]
This is integrated in OdfEdit v2.7
