### ISSUE TITLE
wavpack fixes, misc 

### ISSUE THREAD

**Issue by kwhite-uottawa** [GrandOrgue/OdfEdit#34]
### Attached is a [patch](https://github.com/GrandOrgue/OdfEdit/files/12910212/patch.zip) against v2.6  that:

1. fixes some wavpack decoding issues
2. adds a toggle to limit crossfades for older GO versions
3. resizes the Viewer window when text wraps
4. consider `midi-pitch` a fixed point number

### wavpack
Some wavpack files have an empty `wvpk` block at the end, where the block_index is 0.  The current code then changes the samplerate to 6000Hz.  The attached patch ignores every `wvpk` block for sample rate changes except the first.

`smpl` blocks, etc. can be in either the RIFF_HEADER or RIFF_TRAILER.  Make sure to decode those (an `& 0x3f` is also required).  The attached patch adds the mask and adds RIFF_TRAILER blocks.

### crossfades

GrandOrgue versions earlier than 3.13.0 do not support Crossfades greater than 120ms.  Add a configuration toggle to support these users.

### viewer resize

Samples that have long filenames, and include multiple loops and/or cue points tend to wrap in the Viewer window.  It's then not obvious that there is text not displayed.  Resize the window to display all text.

### midi-pitch

This is a fixed-point number.  Whether the extra precision is necessary or not, well... Other HW->GO conversions (eg: Andrew Hall's) have used the converted floating point value for `Tuning`.

--------------------
**Great work** I find OdfEdit really useful!

[patch.zip](https://github.com/GrandOrgue/OdfEdit/files/12910212/patch.zip)

**Comment by eturpault** [comment]
Thank you @kwhite-uottawa for these good suggestions, and I am glad you are finding OdfEdit useful !
About the wavpack decoding, the specification I found (WavPack5FileFormat.pdf) is not very clear, so your improvements are welcome. I will take also the midi pitch number format.
About the crossfades maximum values, I prefer to not take your patch, it makes heavier the code whereas the solution is to update its GrandOrgue version. I don't intend to introduce in OdfEdit special managements depending on the GO version, I do consider that the user is always using the lastest GO version.
As far as the vertical size of the viewer is concerned, it could indeed be improved. I'm going to set up a vertical scrollbar for displaying wav file metadata instead.

**Comment by eturpault** [comment]
Parts of this patch (wavpack and midi-pitch) are integrated in OdfEdit v2.7.
