### ISSUE TITLE
Pipe Release and Attack files linked incorrectly/not at all

### ISSUE THREAD

**Issue by QbitCreator** [GrandOrgue/OdfEdit#35]
Hello, I have tried to convert multiple ODFs (Cembalo Mietke, Cembalo Ruckers, Prytanée Demo and Święta Lipka) from Hauptwerk to Grand Orgue and always have similar issues. I have no knowledge of the structure of Hauptwerk ODFs, but some of GrandOrgue ODFs, so I don't know what is really defined in what way in the original Hauptwerk ODF.

Theres always a mixture of these two issues with the samplefile-linking:

1. All Attack sample links for a rank are missing. E. g. lines like "Pipe001=..\OrganInstallationPackages\000377\pipe\8dole\036-c.wav" are non-existent. If one pipe of a rank is affected, all pipes of given rank are affected.
Example from the conversion of the Mietke ODF: 
```
[Rank001]
Name=8 - lower manual
FirstMidiNoteNumber=36
NumberOfLogicalPipes=54
WindchestGroup=1
Percussive=N
Pipe001LoopCrossfadeLength=40
Pipe001ReleaseCount=4
Pipe001ReleaseCrossfadeLength=8
Pipe001Release001=..\OrganInstallationPackages\000377\pipe\8dole\rel99999\036-c.wav
Pipe001Release002MaxKeyPressTime=5000
Pipe001Release003MaxKeyPressTime=2100
Pipe001Release004MaxKeyPressTime=800

...
```

2. Some or all Release sample links for a rank are missing. 
If only some are missing, then those are the ones where the folders of the release sample files are also empty. In that case, Pipe001ReleaseCount=4 may be set for example and also defined with MaxKeyPressTime etc, although some of the folders are empty.  If one pipe of a rank is affected, all pipes of given rank are affected exactly the same way.
Example from the conversion of the Mietke ODF:
```
[Rank005]
Name=Pleno
FirstMidiNoteNumber=36
NumberOfLogicalPipes=54
WindchestGroup=1
Percussive=N
Pipe001LoopCrossfadeLength=40
Pipe001=..\OrganInstallationPackages\000377\pipe\pleno\036-c.wav
Pipe001LoadRelease=N
Pipe001ReleaseCount=4
Pipe001ReleaseCrossfadeLength=8
Pipe001Release001MaxKeyPressTime=5400
Pipe001Release002=..\OrganInstallationPackages\000377\pipe\pleno\rel99999\036-c.wav
Pipe001Release003MaxKeyPressTime=2500
Pipe001Release004MaxKeyPressTime=980

...
```

Another example from the conversion of the Prytanée Demo ODF with both problems:
```
[Rank001]
Name=Rear: 1.Pos Cromorne
FirstMidiNoteNumber=36
NumberOfLogicalPipes=54
WindchestGroup=2
Percussive=N
Pipe001Gain=1.4
Pipe001LoopCrossfadeLength=124
Pipe001ReleaseCount=3
Pipe001ReleaseCrossfadeLength=88
Pipe001Release001MaxKeyPressTime=443
Pipe001Release002MaxKeyPressTime=163

...
```
I would appreciate any help and can provide further details if needed!

**Comment by eturpault** [comment]
I tried with the Prytanée Demo that I have on my computer, and OdfEdit v2.6, I don't reproduce what you are observing, In get this Rank001 section for example : 

```
[Rank001]
Name=Rear: 1.Pos Cromorne
FirstMidiNoteNumber=36
NumberOfLogicalPipes=54
WindchestGroup=2
Percussive=N
Pipe001Gain=1.4
Pipe001LoopCrossfadeLength=124
Pipe001=..\OrganInstallationPackages\002300\pipes\Positif\positif_Cromorne8\Rea_positif_Cromorne8\036-c.wav
Pipe001LoadRelease=N
Pipe001ReleaseCount=3
Pipe001ReleaseCrossfadeLength=88
Pipe001Release001=..\OrganInstallationPackages\002300\pipes\Positif\positif_Cromorne8\Rea_positif_Cromorne8\rel00450\036-c.wav
Pipe001Release001MaxKeyPressTime=443
Pipe001Release002=..\OrganInstallationPackages\002300\pipes\Positif\positif_Cromorne8\Rea_positif_Cromorne8\rel00170\036-c.wav
Pipe001Release002MaxKeyPressTime=163
Pipe001Release003=..\OrganInstallationPackages\002300\pipes\Positif\positif_Cromorne8\Rea_positif_Cromorne8\rel99999\036-c.wav
```

The issue that you are describing looks like OdfEdit does not find the sample files in your computer. If the sample files are not present in your computer in the expected folder, OdfEdit will not create the Pipe attack or release attribute for these files.
Are you sure to have completely uncompressed the archive of the sample sets ? For example do you have actually the sample files of the Rank001 in the folders mentioned above ?

**Comment by QbitCreator** [comment]
Thank you very much for your answer! I think you are right. I just tried it on my other PC and now it seems to do it correctly. Probably had something to do with my folder structure in some way...
