### ISSUE TITLE
Pipe001LoopCrossfadeLength is too high after conversion

### ISSUE THREAD

**Issue by QbitCreator** [GrandOrgue/OdfEdit#36]
I have an issue with the file generated from the Prytanée Demo. When I try to import it, it tells me the following and stops to open the file:
16.10.2023 21:43:27: 21:43:27: Fehler: Werteüberschreitung in Abschnitt 'Rank001' Eintrag 'Pipe001LoopCrossfadeLength': 124

Sorry that it's not the english logs, but it basically tells that the value Pipe001LoopCrossfadeLength is too high... 
Any idea?

**Comment by oleg68** [comment]
Use Grandorgue 3.13.0 or above.

**Comment by eturpault** [comment]
It is because you are using OdfEdit v2.6 and a version of GrandOrgue earlier than v3.13.0-1.
In GrandOrgue v3.13.0-1 the maximum values for Loop/ReleaseCrossfadeLength have changed from 120/200 to 3000/3000 and OdfEdit v2.6 takes it into account.

**Comment by QbitCreator** [comment]
Ohhh, thanks alot, this helps very much!
