### ISSUE TITLE
Feature request: Set MIDIInputNumber for Manuals and Enclosures

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/OdfEdit#39]
It would be nice if the MIDIInputNumber was set for converted manuals and (real) enclosures (not the ones used for voicing adjustments).

For the manuals the MIDIInputNumber=1 is used for indicating the pedal, MIDIInputNumber=2 is the lowest manual, MIDIInputNumber=3 the next and so on.

For enclosures (real swell boxes) the numbering should also start with MIDIInputNumber=1 for the leftmost swell pedal and increment for each next.

**Comment by eturpault** [comment]
Ok I will add it in OdfEdit v2.9, thanks @larspalo for the proposal.
For enclosures, in the HW ODF syntax there is none attribute permitting to know the position of the swell pedals on the organ console, so if there are several enclosures I can set the MIDIInputNumber value based on their order of appearance, which is not ideal, else I can try to use the X,Y coordinates of the enclosures in the panel to find their physical order. What do you think ?

**Comment by larspalo** [comment]
> if there are several enclosures I can try to find their physical order to sorting them according to the order of their PositionX + PositionY value

Yes, that would certainly work. I don't know anything about the HW "standard" layout if it even exists, but for GO it would usually be enough to look at what ends up on the main panel.

**Comment by eturpault** [comment]
This is what I implemented and can be tested with the binary shared here : https://github.com/GrandOrgue/OdfEdit/issues/28#issuecomment-1902812659
I tested it with the Sonus Paradisi Billerbeck sample set which has 3 swell pedals (defined in two secondary panels), it works well.

For my knowledge, in which cases this value MIDIInputNumber is usefull ?

**Comment by larspalo** [comment]
> For my knowledge, in which cases this value MIDIInputNumber is useful

In the File->Settings... dialog you have the Initial MIDI tab. There you can pre-configure what keyboards you want to have connected to pedal, first manual and some other things like enclosures and a few setter elements. If the correct MIDIInputNumber is set in the sample set it makes organ configuration somewhat quicker for new organs that you open/load as it will respect your initial MIDI configuration. Many things likely still need further manual configuration, but it's nice when the on-screen keyboards just respond to the correct console keyboard immediately... I've just recently realized the importance of the MIDIInputNumber myself, even though it's been around for quite a long time!

**Comment by eturpault** [comment]
Implemented in OdfEdit v2.9
