### ISSUE TITLE
App not working in version 2.9 after adoption of sounddevice

### ISSUE THREAD

**Issue by raimondl61** [GrandOrgue/OdfEdit#42]
Hi, 
I'm working on Ubuntu 22.04 LTS.
I've installed "pip" via "sudo apt install python3-pip"
I've installed "sounddevice" via "python3 -m pip install sounddevice"
The app still not working with the following error:

Traceback (most recent call last):
  File "OdfEdit.py", line 165, in <module>
    import sounddevice as sd                   # install with : pip install sounddevice
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "sounddevice.py", line 71, in <module>
OSError: PortAudio library not found
[5572] Failed to execute script 'OdfEdit' due to unhandled exception!_

Could you please help me to make the app working?
Many thanks

**Comment by eturpault** [comment]
I tested OdfEdit v2.9 in Ubuntu 22.04 LTS as well and it works.
It seems that you have to install PortAudio library on your Linux machine, try this command : 
apt-get install portaudio19-dev python-all-dev
as indicated here : https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/scripts/readme-gen/templates/install_portaudio.tmpl.rst

**Comment by eturpault** [comment]
If it does not work, try this : 

> sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
> sudo apt-get install ffmpeg libav-tools

found here : https://askubuntu.com/questions/736238/how-do-i-install-and-setup-the-environment-for-using-portaudio

**Comment by raimondl61** [comment]
Hi Eric,

The first answer soved my problem.
Thanks a lot!!!

**Comment by jason-barba** [comment]
I go on installing and installing and installing packets...

Now I seam to miss ./resources/OdfEdit.png

I must have gone astray somewhere.

**Comment by eturpault** [comment]
Are you executing OdfEdit.py with Python engine or with the binary of OdfEdit ?
In the first case, you have to recover the full source code in the assets of the release page : https://github.com/GrandOrgue/OdfEdit/archive/refs/tags/v2.9.zip

**Comment by jason-barba** [comment]
The first, i.e. python 3 ./OdfEdit.py

**Comment by eturpault** [comment]
Yes there is binary for Linux (tested in Ubuntu), it is available in the assets of the release page https://github.com/GrandOrgue/OdfEdit/releases/tag/v2.9, it is the file OdfEdit-2.9-linux.zip

**Comment by jason-barba** [comment]
OK :-)
Ubuntu for dummies question: How do install the Linux binary? And what is the execute command?

**Comment by eturpault** [comment]
Just unzip the unique binary file OdfEdit which is inside the archive OdfEdit-2.9-linux.zip, then double-click on it to execute it.
If it does not want to run, right click on the OdfEdit binary file, in the properties menu there is an option to allow the execution of the file (I don't have Ubuntu running in front of me, I don't remember the name of the option).

**Comment by jason-barba** [comment]
Thanks for advice. Back when I have tried that.

**Comment by jason-barba** [comment]
Success! Thansk a lot.
