### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Psi58** [GrandOrgue/OdfEdit#43]
Windows Defender reckons that Trojan:Win32/Phonzy.B!ml is in the zip file of v2.9:

![image](https://github.com/GrandOrgue/OdfEdit/assets/130241113/89e441e7-f2dc-4390-958f-2a795ca00ff3)

Malwarebytes doesn't flag a problem

**Comment by eturpault** [comment]
Indeed, this is strange.
I generate the executables of OdfEdit with PyInstaller. When I generated two days ago the .exe file, Windows Defender didn't detected an issue. Now I have the same issue as you...
It think it is a false detection, as discussed here : https://stackoverflow.com/questions/77003989/virus-was-found-in-my-python-program-after-recompiling-into-exe
The safest way is to execute OdfEdit.py with Python engine as described in the Readme file.

**Comment by Psi58** [comment]
Thanks, using native python as a workaround is successful (and I learnt something...!)
