### ISSUE TITLE
SP Ruckers Demo - Keys below 36-C

### ISSUE THREAD

**Issue by pgwid-og** [GrandOrgue/OdfEdit#45]
When converting this harpsichord sample (https://www.sonusparadisi.cz/en/blog/cembalo-ruckers-demo/) I noticed that the two ranks were generated from 36-C onwards. But the keyboard and the corresponding samples are from 31-G.
I am not that big harpsichord player, but nevertheless I'd like to indicate this to you. May be you want to improve your algorithms to handle notes below 36-C as well?
Kind regards, Oliver

P.S. If you try the sample set, don't worry about the updated ODF. I tried the update in HW and it was faulty on my PC.

**Comment by eturpault** [comment]
Indeed there is an issue in OdfEdit when converting from HW to GO the keyboards which does not start by MIDI note 36, as discussed [in another issue](https://github.com/GrandOrgue/OdfEdit/issues/41#issuecomment-1928527323) for the St Carlo Brescia sample set. I will fix it in the next release.
Thank you for reporting the issue with this harpischord sample set, I will use it to valide the fix.

**Comment by eturpault** [comment]
I have fixed the issue in OdfEdit with keyboards not starting by MIDI note 36, it will be available in next OdfEdit release.
Here is the ODF generated with this fix from the initial HW ODF (not the updated one) : [Cembalo Ruckers DEMO.zip](https://github.com/GrandOrgue/OdfEdit/files/14303730/Cembalo.Ruckers.DEMO.zip)

**Comment by eturpault** [comment]
Fixed in OdfEdit v2.10.
