### ISSUE TITLE
Deleting a rank does not renumber existing ranks

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/OdfEdit#47]
After I deleted an (invalid) rank Rank084 (see #46) I receive an error ``Missing required value section 'Rank084' entry 'FirstMidiNoteNumber``

I expected that all ranks with higher numbers would be renumbered N -> N-1 and all references to them would be updated.

**Comment by eturpault** [comment]
The automatic ranks renumbering after the deletion of one section is not implemented today in OdfEdit, I can add it.
This would have to be done for the following types of sections : 

- Enclosure, General, Panel, PanelElement, PanelImage, Rank, Switch, Tremulant, WindchestGroup, 

and note done for the following : 

- Coupler, Divisional, DivisionalCoupler, Manual, Stop

Do you agree ?

**Comment by oleg68** [comment]
> Do you agree ?

Yes, I do.

**Comment by eturpault** [comment]
Implemented in OdfEdit v2.10.

**Comment by eturpault** [comment]
@oleg68 please let me know if it works as you expected. Other good idea to improve OdfEdit features are welcome from you, thanks.

**Comment by oleg68** [comment]
@eturpault Yes, it does. Thank you.
