### ISSUE TITLE
Delimiter duplicated in HW conversion

### ISSUE THREAD

**Issue by Psi58** [GrandOrgue/OdfEdit#49]
I'm trying to convert https://www.pipeloops.com//product_info.php?cPath=23&products_id=64.

The samples are not found; there appear to be extra spurious "/" delimiters in many of the paths of the GO ODF. 
EG, from the log:
`WARNING : in package ID 2049, file not found : P_Subbass16//Front//Main/036-C.wav`

Apologies if this is just user error, this is my first time to attempt HW2GO conversion using ODFEdit.

Using Python executable of ODFEdit v2.10 on W10.

Thanks.

**Comment by eturpault** [comment]
I downloaded this sample set and made the test, indeed in the original HW ODF the files path contain double slashes delimiters, it is the first time I see this. Probably it is supported by Hauptwerk, but it is not by OdfEdit and by Windows/Linux (I see it is supported by GrandOrgue).
What you can do is to edit the file "Pipeloops Romantic Village Church Organ.Organ_Hauptwerk_xml" (with Notepad++ for example) which is located in the folder OrganDefinitions of the sample set (firstly make a copy of it) and inside replace all the // by /, and save the modifications. After that you will be able to load the corrected HW ODF in OdfEdit without issue, and to load the generated GO ODF in GrandOrgue without issue as well.

**Comment by eturpault** [comment]
OdfEdit v2.11 supports "//" in the files paths.
