### ISSUE TITLE
Missing tkinter

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/OdfEdit#5]
Apparently this is not always installed by default (I use Mint). To resolve run `sudo apt-get install python3-tk`.

**Comment by rousseldenis** [comment]
@ahall41 Thanks reporting this. I need to finish this https://github.com/GrandOrgue/ODFEdit/pull/3

And it will be solved

**Comment by rousseldenis** [comment]
Ooops no. But this should be set in a README file.

**Comment by eturpault** [comment]
README updated with this additional mention for Linux.
