### ISSUE TITLE
Conversion of Braunschweig-Querum

### ISSUE THREAD

**Issue by wsc44** [GrandOrgue/OdfEdit#51]
I converted the free sample set Braunschweig-Querum by Pipeloops (https://www.pipeloops.com//assets/Pipeloops_Romantic_Village_Church_Organ.CompPkg.Hauptwerk.rar). The blower slider does not work. As far as i can see no code is generated to support that feature. Apart from that everything seems to work fine. Very nice result!  :-)) 
Please have a look into this matter.

**Comment by eturpault** [comment]
This is because in the HW ODF the blower noise is controlled by a switch which is has no graphical interface and thus is not clickable (it is engaged by default). I made the choise to not convert from HW to GO the non clickable switches, to avoid to have features that the user cannot control. Furthermore, the blower noise is an accessory feature, I think it is not a big miss to not have it.

**Comment by wsc44** [comment]
Have you opened the control panel? - It's not a switch (like the one shown on the console panel) but a slider. All sliders, with the exception of the detune-slider [a strange idea which seems to have become a fashion now] and the blower slider, are working perfectly. I still do think that it would be worthwhile to find out while the parser has skipped only that slider.

**Comment by eturpault** [comment]
Ok I see, there is no visible button to control the blower noise state (there is a hidden button always enabled), however there is a slider to control the audio volume of the blower noise. I have found a way to manage in the next version of OdfEdit this use case where a switch is not visible/clickable, engaged by default and controlling noise samples.
OdfEdit does not parse the sliders, it parses the switches of the HW ODF, if a switch is controlling a feature which can be converted in GO the associated objects are converted to GO (switches, stop, windchest, enclosure/slider, ...).
Now the blower noise is audible and its audio volume can be controlled by the slider "Blower". Here is the ODF generated by OdfEdit v2.12beta (it has also the header including the conversion options status that you suggested to add in https://github.com/GrandOrgue/OdfEdit/discussions/52#discussion-6533136) :
[Pipeloops Romantic Village Church Organ.zip](https://github.com/GrandOrgue/OdfEdit/files/15052076/Pipeloops.Romantic.Village.Church.Organ.zip)

**Comment by wsc44** [comment]
Thanks for ODF and header data implementation!
