### ISSUE TITLE
Conversion Oloron-Sainte-Marie (DEMO-version)

### ISSUE THREAD

**Issue by wsc44** [GrandOrgue/OdfEdit#55]
The conversion of Oloron-Sainte-Marie (https://piotrgrabowski.pl/oloron-sainte-marie/) did not generate the first keyboard (Totalisateur), maybe due to the fact that it has no stops of its own. Some of the accessories, not directly connected to the first keyboard, are also missing.
Second and third keyboard are O.K.

**Comment by eturpault** [comment]
Hauptwerk ODF has Keyboard sections acting on a Division section or another Keyboard section, through a KeyAction section.
Stops sections are linked to Division sections.

GrandOrgue ODF has Manual sections, which can act on another Manual section through Coupler sections. 
Stops sections are linked to Manual sections

So the conversion from HW to GO is not a 1 to 1 conversion.
Currently OdfEdit converts only the first HW Keyboard acting on each HW Division to a GO Manual. So far it has been sufficient.

But I see that it is no sufficient for this sample set which has a Keyboard not directly linked to a Divisional, and which can act on "Grand Orgue" or "Récit" keyboards depending on a coupler selection.
I will see how OdfEdit can build Manual and Coupler sections fitting better to the HW ODF definition.
Thanks for this interresting use case.

**Comment by eturpault** [comment]
Which accessories are missing according to your observation ?
HW features cannot be all converted to GO features.

**Comment by wsc44** [comment]
Didn't expect that GrandOrgue and Hauptwerk ODF's nowadays differ so much in the way they organize their basic ODF structure.

The following accessories are not working:
- Orage: very rarely used of course & maybe one of those HW-specific items;
- Tremulant: On activation the motor of the tremulant engages in the background, but no tremmed organ samples are played;
- Appels d'anches: That's a tricky one because I wondered why I couldn't reproduce the malfunction again today. It took me some time to find out the reason why: As soon as one selects "Enable appels d'anches on organ load" (disabled by default) on the settings panel the position of the  appels d'anches no longer influences the behaviour of the "red" stops. They are then always active. Additionaly, after reloading the organ, even if "Enable ... on organ load" is set, the pedals are not shown in pressed down position.

One thing I forgot to mention: PG offers GO-ODFs for his non-encrypted sample sets (https://piotrgrabowski.pl/grandorgue-versions/). They offer reduced functionality, explained by him in an extra help-file. But since he made those ODF's, some improvements (crossfade etc.) have been implemented into GO and which are of course not reflected in PG's own GO-ODFs. That's why I think that it will make sense to generate new ODF's via OdfEdit. Apart from that, in case of Oloron you get warnings when loading the sample set which I gather are connected to GO-improvements.

Of course it would be nice to have the Load/Save Preset function from the settings page too, but alas ... one of those HW-specific features?

Thanks for keeping up the good work!

**Comment by eturpault** [comment]
About the not working accessories :
- Orage : in the HW ODF, when it is engaged it presses simultaneously the keys MIDI note 36 to 43 of the first keyboard "Accoupleur". I don't think it is possible to specify such an action in the GO ODF.
- Tremulant : there is no usual tremulant defined in the HW ODF. When the Tremulant switch is engaged, it plays an ondulating noise which added to the pipes sound creates like a tremulant effect. This is converted by OdfEdit.
- Appel d'anches : in the HW ODF this switch exists for each keyboard : Pédale, Grand Orgue, Récit. OdfEdit converts only the one of the Grand Orgue keyboard as in the demo sample set only this keyboard has a reed stop (Clairon 4). Strangely in the HW ODF this switch acts also on the stops Octave 4, Doublette 2 and Plein jeu harmonique which are not reed stops. The switch "Enable Appels d'anches on load" should not be converted by OdfEdit as it has a unusual switch effect which cannot be converted in GO ODF (to set the initial status of another switch). I will change this for the next OdfEdit version.

**Comment by larspalo** [comment]
@eturpault The Orage effect _is_ possible to achieve in GO, but not exactly in that manner (the lowest keys of some manual, often the pedal, would be physically pressed) and my realization of it isn't something I'd recommend using as it's an extremely strained solution that uses up many of the available stops. Anyway, for academic purposes, here is a demonstration of how one currently can implement it: [TestEffectOrage.zip](https://github.com/GrandOrgue/OdfEdit/files/15281976/TestEffectOrage.zip).

For the Appels. The Jeux d'Combinaison (the stops that would be activated by the Appel) didn't always include only reed stops. Also higher pitched octaves and different aliquots/mutation/compound stops could be included. The Jeux de Fonds would most of the time only include the 16, 8 and 4 foot "foundation" stops that are flute pipes, but for a Récit that could possibly also include the Basson-Hautbois, Voix Humaine, Clarinette and similar "soft" reeds. There's a pretty good writeup at https://www.sonusparadisi.cz/en/blog/registration-of-french-romantic-music/ that accurately describes the system just as I've learned it (as an organist).

**Comment by eturpault** [comment]
Very interresting this article.
In Oloron Sainte Marie, according to the HW ODF, the "Appel d'anches" of the Pédale keyboard acts on the stops "Bombarde 16" and "Trompette 8".
On the Récit keyboard, it acts on the stops "Octavin 2", "Basson et Hautbois 8" and "Trompette 8". So the Octavin 2 of the Récit is also included in the reeds.

Your implementation of an Orage effect is indeed adding several Stops, it is a good idea to manage this mechanism. An alternate way could be to have a Coupler section not attached to a particular Manual and able to apply a permanent effect on a given range of keys when it is engaged (new feature).
I think I will not use copy your implemention for OdfEdit as it would add complexity to the SW for a feature which is very rarely used as said by @wsc44, I agree with that. This effect doesn't look very pleasant in my opinion.

**Comment by larspalo** [comment]
> I think I will not use copy your implemention for OdfEdit

I can fully understand that! It would indeed be better to have a separate feature in GO that could mimic the actual de-pressing of any number of keys of any manual controlled by it. Until such a feature exist, I really wouldn't bother with the Orage effect! I just implemented it to show that it already could be achieved but in a very inconvenient and convoluted way, not to be recommended.

**Comment by wsc44** [comment]
Thanks @larspalo for explaining the appels and for the interesting Orage-implementation.
 I'd like to add that in former times the terms "Anches PED/GO/REC" were also sometimes used when in fact it meant to activate the "Jeux de combinaisons" of the corresponding manuals (ex. Sainte-Clotilde in Paris by ACC). In case of Oloron, PG probably got his information ("Anches ...") from this site (https://oloron-orgues.fr/cath%c3%a9drale.html), wheras that document (https://oloron-orgues.fr/assets/masterclass2024fr.pdf) gives the more precise description ("Jeux de combinaisons"). -  Hope that OdfEdit will manage that "switchology"  in one of the next revisions.

Tremulant: The noise of the tremulant mechanism mixing with untremmed samples does not add up to the desired effect. Each Recit stop has its own tremulant samples in the directories AT0_D, AT0_F and AT0_R. PG demonstrates the use of these directories in his GO-ODF.

**Comment by eturpault** [comment]
@larspalo @oleg68 : the conversion from HW to GO of the first keyboard "Accoupleur" of this sample set is not simple. Maybe I found a solution to manage it in OdfEdit but it is not easy to implement. Before to start this development, I would like to be sure that an easier solution (more close to how it is implemented in the HW ODF) is possible or not.

The keyboards configuration in this sample set is the following (converted from HW to ODF with current implementation of OdfEdit v2.12 beta) :

Manual001, visible, first keyboard of the console (called Accoupleur)
Manual002, not visible (called Accoupleur EXEC)
Manual003, visible, second keyboard of the console (Grand Orgue division)
Manual004, visible, third keyboard of the console (Récit division)

Coupler101 ("I unisson") always engaged, connecting Manual001 to Manual002
Coupler102 ("I OG", DestinationKeyshift=-12) controlled by the "I OG" switch, connecting Manual001 to Manual002
Coupler201 ("GO/I"), controlled by the "GO/I" switch, connecting Manual002 to Manual003
Coupler202 ("R/I"), controlled by the "R/I" switch, connecting Manual002 to Manual004

With GrandOrgue :
When Coupler201 is engaged, the keys press on Manual001 are not reflected on Manual003
When Coupler202 is engaged, the keys press on Manual001 are not reflected on Manual004
I tried by setting UnissonOff=Y in Coupler201 and Coupler202 but it changes nothing. I don't know what this attribute is used to.
Is there a way to get it working (to have Manual001 keys press forwarded to Manual003 or Manual004 through Manual002) ?

If not, OdfEdit will have to generate the following couplers structure which is very different from the HW one (ignoring the Manual002) :
Coupler101 ("GO/I") controlled by the "GO/I" switch, connecting Manual001 to Manual003
Coupler102 ("R/I") controlled by the "R/I" switch, connecting Manual001 to Manual004
Coupler103 ("GO/I + I OG") controlled by the "GO/I" and "I OG" switches, connecting Manual001 to Manual003 with -12 keys shift
Coupler104 ("R/I + I OG") controlled by the "R/I" and "I OG" switches, connecting Manual001 to Manual004 with -12 keys shift

**Comment by larspalo** [comment]
> Is there a way to get it working (to have Manual001 keys press forwarded to Manual003 or Manual004 through Manual002) ?

Usually this is done by setting the CoupleToSubsequentUnisonIntermanualCouplers et al (Upward and Downward) for passing on the keypress correctly to other couplers, this achieves the "couple through" effect.

By only reading the description on https://piotrgrabowski.pl/oloron-sainte-marie/ it's very hard for me to say anything for sure, but why on earth would you need the hidden Manual002 and all the hidden complexities? In the GO version that Piotr supplies there is only 3 manuals and a pedal. From the description only, I cannot really see any need for a fourth (hidden second) manual, is it there in the HW version?

**Comment by eturpault** [comment]
Yes this hidden keyboard (and the couplers arrangment that I described) is actually present in the HW ODF of Piotr Grabowski. OdfEdit converted them in GO as they are defined in HW.

Thank you very much for the information about the usage of the CoupleToSubsequent... attributes, I was ignoring their usage.
Setting in Coupler101 :

> CoupleToSubsequentUnisonIntermanualCouplers=Y

and setting in Coupler102 :
> DestinationKeyshift=-12
> CoupleToSubsequentUnisonIntermanualCouplers=Y
> CoupleToSubsequentDownwardIntermanualCouplers=Y

it works perfectly as expected !

@wsc44 : here is the ODF with working first keyboard and the "Appel d'anches: GO" working as well, generated with my current implementation of OdfEdit v2.12beta. Do you see other issues ?
[Oloron-Sainte-Marie (demo).zip](https://github.com/GrandOrgue/OdfEdit/files/15284244/Oloron-Sainte-Marie.demo.zip)

**Comment by eturpault** [comment]
I see that setting CoupleToSubsequentDownwardIntermanualCouplers=Y in Coupler102 is not needed.

**Comment by wsc44** [comment]
@eturpault: I tested the new ODF. Some remarks:
- First manual (Totalisateur): The coupling mechanism to GO and REC works as intended. The "Octave Grave" coupler works too, but when activated and a key is pressed the suboctave key on the Totalisateur-keyboard is not highlighted. The coupled keyboards do show the pressed down suboctave. It should be shown on the Totalisateur-keyboard too because it is a mechanical coupling mechanism. Totalisateur keyboard does not produce any key noises.

- Key noises: In general I can hear key noises only from front perspective. Rear & dry perspective do not contain any key noises. 

- Appels (Jeux de. Comb.): Only GO-appel is selectable? Functionality O.K., but I miss REC and PED.

- When moving the "red" stop knobs (Jeux de Comb.) the stop action sound is only played when the corresponding appel (GO/
REC)  is activated. In reality the sound of the moving stop knobs is not connected to the appel mechanism.

- According to file header no conversion of tremulant samples so I couldn't test that feature. 

- Simple/Left/Right Jamb: Some stops are highlighted by default (some of them not selectable in demo). Maybe initialization fault?

- Settings panel: "Enable appels d'anches on organ load" is no longer selectable. Is that intentional?

I'd like to add that I do check the ODF's against the full sample set (which I've bought recently). Please let me know if you can't reproduce any of the aforementioned items. I've checked the functionality of all items against PG's GO-ODF (demo). I don't expect that the full sample set behaves different to the demo set, but never say never ...

**Comment by wsc44** [comment]
Bass coupling: I wonder where he has hidden this feature in his HW ODF. Because I doubt that he has implemented it in the GO-ODF demo (!) version without having it implemented in his HW-ODF in one way or another.  But true, in the end not so important.

Key noises audio chanel: same as bass coupling, but a bit more important.

Tremmed samples:  Bad news indeed.

Appel d'anches: O.K. for PED, but not O.K. for REC (Voix humaine is part of the Jeux de combinaisons).

Thanks for the info & research!

**Comment by eturpault** [comment]
In the Demo HW ODF the "Appel d'anches" for REC is acting on "Octavin 2", "Basson et Hautbois 8" and "Trompette 8", not on "Voix humaine 8". It is the same in the GO ODF provided by Piotr Grabowski (both demo and full).

**Comment by wsc44** [comment]
Correct, my bad.

**Comment by eturpault** [comment]
The missing keyboard issue is fixed in OdfEdit v2.12, and OdfEdit v2.13 converts the tremmed samples.
