### ISSUE TITLE
Conversion of Landau generates errors

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/OdfEdit#56]
I tried converting the latest OdfEdit (1.11) on the new Landau set from Piotr Grabowski. When opened with latest GO, I get complaints 
`Tue 07 May 2024 18:38:58 BST: 18:38:58: Error: Switch 2 already assigned to Switch003`
Another HW feature which needs to be investigated? [GoOdf doesn't recognise this as an error either].
Not urgent - there's a version generated with an older OdfEdit which is OK for evaluation purposes on MPS Orgelseite.

**Comment by larspalo** [comment]
> GoOdf doesn't recognise this as an error either

@ahall41 Currently there's not much of logic checking implemented in GoOdf except for value types and ranges. Warnings are currently even less implemented (but it's definitely going to change over time). However, the actually read and written switches in/from GoOdf _should_ adhere to GO standard. Did you try writing the .organ file back from GoOdf and compare the results?

**Comment by larspalo** [comment]
@ahall41 I downloaded and tested this myself and apparently the same switch is referenced twice for that OR function! I'll try to fix that fault! Thanks for reporting it.

**Comment by ahall41** [comment]
> Did you try writing the .organ file back from GoOdf and compare the results?

I just did, and get the same error. I'm guessing GoOdf won't let you actually create

I find that every time I try to 'transform' an organ, there is some unexpected feature (or maybe me misunderstanding) I haven't yet encountered! I was planning to script this, but thought I'd give GoOdf a try first - and then someone has already done it (probably OK for an evaluation).

**Comment by eturpault** [comment]
Piotr Graboswki is used to building quite complex switches networks, there is probably a weakness in OdfEdit for handling switches from this new sample set, I will look into it and fix it.
Thanks for the report.

**Comment by eturpault** [comment]
@ahall41 For OdfEdit v2.12 on which I am working, I reworked and improved the way to convert the switches networks from HW to GO (making it also faster than before) and there is no more the error that you reported with double references to a switch when loading the generated ODF in GO. So it is a positive side effect of this rework.
But there is a problem with this demo sample set. The buttons controlling available stops are displayed with transparent images (taken in the folder \OrganInstallationPackages\002529\Images\T), so one cannot see in the stops panels which stops are engaged.

**Comment by ahall41** [comment]
That's interesting. I've now run this through my own scripts. which use some guesswork algorithms, and the images are coming out correctly. Folders Console, Jamb and SimpleJamb ...

**Comment by eturpault** [comment]
The issue reported in the first comment is not reproduced with OdfEdit v2.13.
