### ISSUE TITLE
Problem with the last key of manual, if it is a sharp key

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/OdfEdit#58]
After converting this organ:

https://drive.google.com/file/d/1kETnsTcDM19Lnw15aB0b6GsELzdaDJsp/view

I have to add manually the following lines to Panel000Element001:
ImageOff_LastDis=..\OrganInstallationPackages\002204\images\keys\Up-Sharp.bmp
ImageOn_LastDis=..\OrganInstallationPackages\002204\images\keys\Down-Sharp.bmp

**Comment by eturpault** [comment]
It is fixed in OdfEdit v2.13.
