### ISSUE TITLE
Unable to select multiple items in 2.12 on linux

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/OdfEdit#59]
Earlier I was able to select multiple items (for example, ranks) and delete them.

But now when I select a next item the previous selected item is deselected.

**Comment by eturpault** [comment]
I am surprised by that, OdfEdit is not made to permit the selection of multiple items in the sections list or tree.
I just did the test with OdfEdit 2.11 in Linux and I am not able to select multiple items. How did you did that ?

**Comment by eturpault** [comment]
In order to facilitate the deletion of several sections, OdfEdit could react to the keyboard Del key press to make the same action as clicking on the Delete button. Are you interrested by that ?

**Comment by eturpault** [comment]
In OdfEdit v2.13, pressing the Delete key of the keyboard does the same action as clicking on the Delete button.
