### ISSUE TITLE
Risk for the Computer / Virus?

### ISSUE THREAD

**Issue by Micha77HH** [GrandOrgue/OdfEdit#61]
Ther ist noch chance to user Your Programm, because my Virus Protection say the Programm is a risk for the Computer.

![image](https://github.com/user-attachments/assets/6a144876-37bb-4025-a4bc-441a5c684db0)

Please Fix ist, that I can use the Programm.

Greeting 
Michael

**Comment by eturpault** [comment]
This is a false detection. The binary of OdfEdit is generated using [PyInstaller ](https://pyinstaller.org/) who probably adds in the .exe some stuffs which are detected as a risk by some anti-virus. On my computer and the one of other Windows users there is none detected risk.
If you want a fully sure method, you can run OfdEdit with Python engine, as explained in the welcome page of [OdfEdit](https://github.com/GrandOrgue/OdfEdit). OdfEdit is not accessing to Internet and on the computer it is writting only in the edited ODF and a configuration file.
